services:
  json-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_TOKEN=sk-KNo006G2a48UVE3IxFlQEQ
    networks:
      - generator

networks:
  generator:
    driver: bridge
