services:
  json-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_TOKEN=INSERT_TOKEN
    networks:
      - generator

networks:
  generator:
    driver: bridge
